version: "3.8"

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "10000:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  static-api:
    build: .
    ports:
      - "8081:8081"
    env_file:
      - .env
    command: "serve"
    depends_on:
      - postgres
      - static-api-setup

  static-api-setup:
    build: .
    env_file:
      - .env
    command: "fake"
    depends_on:
      - postgres

  dynamic-api:
    build: .
    ports:
      - "8082:8082"
    env_file:
      - .env
    command: ["metrics"]
    depends_on:
      - postgres

volumes:
  pgdata:
