apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ecostars.fullname" . }}-keycloak
  labels:
    {{- include "ecostars.labels" . | nindent 4 }}
    app.kubernetes.io/component: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "ecostars.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: keycloak
  template:
    metadata:
      labels:
        {{- include "ecostars.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: keycloak
    spec:
      containers:
        - name: keycloak
          image: "{{ .Values.keycloak.image.repository }}:{{ .Values.keycloak.image.tag }}"
          imagePullPolicy: {{ .Values.keycloak.image.pullPolicy }}
          command:
            - "/opt/keycloak/bin/kc.sh"
            - "start-dev"
            - "--import-realm"
          env:
            - name: KC_DB
              value: postgres
            - name: KC_DB_URL
              value: "jdbc:postgresql://{{ include "ecostars.fullname" . }}-keycloak-db:5432/keycloak"
            - name: KC_DB_USERNAME
              value: {{ .Values.keycloakDb.auth.username }}
            - name: KC_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "ecostars.fullname" . }}-secrets
                  key: KEYCLOAK_DB_PASSWORD
            - name: KC_HOSTNAME_STRICT
              value: "false"
            - name: KEYCLOAK_ADMIN
              value: {{ .Values.keycloak.auth.adminUser }}
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "ecostars.fullname" . }}-secrets
                  key: KEYCLOAK_ADMIN_PASSWORD
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: realm-config
              mountPath: /opt/keycloak/data/import/realm.json
              subPath: realm.json
      volumes:
        - name: realm-config
          configMap:
            name: {{ include "ecostars.fullname" . }}-keycloak-realm

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ecostars.fullname" . }}-keycloak
  labels:
    {{- include "ecostars.labels" . | nindent 4 }}
    app.kubernetes.io/component: keycloak
spec:
  type: {{ .Values.keycloak.service.type }}
  ports:
    - port: {{ .Values.keycloak.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "ecostars.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: keycloak
