apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ecostars.fullname" . }}-keycloak-realm
  labels:
    {{- include "ecostars.labels" . | nindent 4 }}
data:
  realm.json: |-
    {
      "realm": "ecostars",
      "enabled": true,
      "users": [
        {
          "username": "testuser",
          "enabled": true,
          "emailVerified": true,
          "firstName": "Test",
          "lastName": "User",
          "email": "testuser@example.com",
          "credentials": [
            {
              "type": "password",
              "value": "password",
              "temporary": false
            }
          ],
          "realmRoles": [
            "user"
          ]
        }
      ],
      "roles": {
        "realm": [
          {
            "name": "user",
            "description": "User role"
          },
          {
            "name": "admin",
            "description": "Admin role"
          }
        ]
      },
      "clients": [
        {
          "clientId": "ecostars-client",
          "enabled": true,
          "publicClient": false,
          "secret": "ecostars-secret",
          "directAccessGrantsEnabled": true,
          "standardFlowEnabled": true,
          "redirectUris": [
            "*"
          ],
          "webOrigins": [
            "*"
          ]
        }
      ]
    }
