apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ecostars.fullname" . }}-secrets
  labels:
    {{- include "ecostars.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_PASS: {{ .Values.postgres.auth.password }}
  KEYCLOAK_DB_PASSWORD: {{ .Values.keycloakDb.auth.password }}
  KEYCLOAK_ADMIN_PASSWORD: {{ .Values.keycloak.auth.adminPassword }}
